### ISSUE TITLE
(임시) cicd.yml 

### ISSUE THREAD

**Issue by daadaadaah** [daadaadaah/devlinky#18]
```yml
name: CI_CD

on: [push, pull_request]

jobs:
  FrontEnd-build:
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Load FIREBASE Config (dev)
        run: |
          echo 'FIREBASE_API_KEY=${{ secrets.DEV_FIREBASE_API_KEY }}' >> config/.env.development
          echo 'FIREBASE_AUTH_DOMAIN=${{ secrets.DEV_FIREBASE_AUTH_DOMAIN }}' >> config/.env.development
          echo 'FIREBASE_PROJECT_ID=${{ secrets.DEV_FIREBASE_PROJECT_ID }}' >> config/.env.development
          echo 'FIREBASE_STORAGE_BUCKET=${{ secrets.DEV_FIREBASE_STORAGE_BUCKET }}' >> config/.env.development
          echo 'FIREBASE_DATABASE_URL=${{ secrets.DEV_IREBASE_DATABASE_URL }}' >> config/.env.development
          echo 'FIREBASE_MESSAGING_SENDER_ID=${{ secrets.DEV_FIREBASE_MESSAGING_SENDER_ID }}' >> config/.env.development
          echo 'FIREBASE_APP_ID=${{ secrets.DEV_FIREBASE_APP_ID }}' >> config/.env.development
          echo 'FIREBASE_MEASUREMENT_ID=${{ secrets.DEV_FIREBASE_MEASUREMENT_ID }}' >> config/.env.development
      - name: Unit Test (PR)
        if: github.ref != 'refs/heads/master'
        run: npm run coverage
        env:
          HEADLESS: true
      - name: Unit Test & E2E Test (Merge to Master)
        if: github.ref == 'refs/heads/master'
        run: npm test
        env:
          HEADLESS: true
      - name: Load FIREBASE Config (prod)
        run: |
          echo 'FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}' >> config/.env.production
          echo 'FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}' >> config/.env.production
          echo 'FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}' >> config/.env.production
          echo 'FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}' >> config/.env.production
          echo 'FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}' >> config/.env.production
          echo 'FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}' >> config/.env.production
          echo 'FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}' >> config/.env.production
          echo 'FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}' >> config/.env.production
      - name: Build (prod)
        run: |
          npm run build

```
